PKGDIR	?= ..
L4DIR	?= $(PKGDIR)/../..

EXTRA_TARGET += \
	l4virtio \
	virtqueue \
	client/l4virtio \
	client/virtio-block \
	client/virtio-net \
	server/virtio \
	server/l4virtio \
	server/virtio-block \
	server/virtio-console \
	server/virtio-console-device \
	server/virtio-gpio-device \
	server/virtio-i2c-device \
	server/virtio-rng-device \
	server/virtio-scmi-device

include $(L4DIR)/mk/include.mk
